from __future__ import annotations

from pathlib import Path

import pytest

from schnitzel_stream.ops import graph_wizard as wizard_ops


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def test_load_profile_table_and_filtering(tmp_path: Path):
    repo_root = tmp_path
    _write(
        repo_root / "configs" / "graphs" / "templates" / "demo.yaml",
        "version: 2\nnodes: []\nedges: []\nconfig: {}\n",
    )
    _write(
        repo_root / "configs" / "wizard_profiles" / "a.yaml",
        "\n".join(
            [
                "id: alpha",
                "description: alpha profile",
                "template: configs/graphs/templates/demo.yaml",
                "experimental: false",
            ]
        )
        + "\n",
    )
    _write(
        repo_root / "configs" / "wizard_profiles" / "b.yaml",
        "\n".join(
            [
                "id: beta",
                "description: beta profile",
                "template: configs/graphs/templates/demo.yaml",
                "experimental: true",
            ]
        )
        + "\n",
    )

    table = wizard_ops.load_profile_table(repo_root)
    rows_public = wizard_ops.list_profile_rows(table=table, include_experimental=False)
    rows_all = wizard_ops.list_profile_rows(table=table, include_experimental=True)

    assert [row[0] for row in rows_public] == ["alpha"]
    assert [row[0] for row in rows_all] == ["alpha", "beta"]


def test_generate_graph_injects_overrides_and_provenance(tmp_path: Path):
    repo_root = tmp_path
    _write(
        repo_root / "configs" / "graphs" / "templates" / "file_frames.yaml",
        "\n".join(
            [
                "version: 2",
                "nodes:",
                "  - id: src",
                "    kind: source",
                "    plugin: schnitzel_stream.nodes.dev:StaticSource",
                "    config:",
                "      packets:",
                "        - kind: demo",
                "          source_id: demo01",
                "          payload:",
                "            path: \"${INPUT_PATH}\"",
                "            max_frames: ${MAX_FRAMES}",
                "            loop: ${INPUT_LOOP}",
                "  - id: out",
                "    kind: sink",
                "    plugin: schnitzel_stream.nodes.dev:PrintSink",
                "edges:",
                "  - from: src",
                "    to: out",
                "config: {}",
            ]
        )
        + "\n",
    )
    _write(
        repo_root / "configs" / "wizard_profiles" / "file_frames.yaml",
        "\n".join(
            [
                "id: file_frames",
                "description: file profile",
                "template: configs/graphs/templates/file_frames.yaml",
                "experimental: false",
                "defaults:",
                "  INPUT_PATH: data/default.mp4",
                "  MAX_FRAMES: \"30\"",
                "  INPUT_LOOP: \"false\"",
            ]
        )
        + "\n",
    )

    table = wizard_ops.load_profile_table(repo_root)
    generated = wizard_ops.generate_graph(
        repo_root=repo_root,
        table=table,
        profile_id="file_frames",
        out_path="configs/graphs/generated.yaml",
        allow_experimental=False,
        input_path="data/custom.mp4",
        loop="true",
        max_events=42,
    )

    text = generated.output_path.read_text(encoding="utf-8")
    assert text.startswith("# Generated by graph_wizard v1")
    assert "profile_id: file_frames" in text
    assert 'path: "data/custom.mp4"' in text
    assert "max_frames: 42" in text
    assert "loop: true" in text
    assert generated.overrides["INPUT_PATH"] == "data/custom.mp4"
    assert generated.overrides["MAX_FRAMES"] == "42"


def test_generate_graph_requires_experimental_opt_in(tmp_path: Path):
    repo_root = tmp_path
    _write(
        repo_root / "configs" / "graphs" / "templates" / "demo.yaml",
        "version: 2\nnodes: []\nedges: []\nconfig: {}\n",
    )
    _write(
        repo_root / "configs" / "wizard_profiles" / "exp.yaml",
        "\n".join(
            [
                "id: exp_profile",
                "description: experimental profile",
                "template: configs/graphs/templates/demo.yaml",
                "experimental: true",
            ]
        )
        + "\n",
    )
    table = wizard_ops.load_profile_table(repo_root)

    with pytest.raises(wizard_ops.GraphWizardPreconditionError):
        wizard_ops.generate_graph(
            repo_root=repo_root,
            table=table,
            profile_id="exp_profile",
            out_path="out.yaml",
            allow_experimental=False,
        )

    generated = wizard_ops.generate_graph(
        repo_root=repo_root,
        table=table,
        profile_id="exp_profile",
        out_path="out.yaml",
        allow_experimental=True,
    )
    assert generated.output_path.exists()


def test_validate_graph_file_success_and_failure(tmp_path: Path):
    repo_root = tmp_path
    good = repo_root / "good.yaml"
    good.write_text(
        "\n".join(
            [
                "version: 2",
                "nodes:",
                "  - id: src",
                "    kind: source",
                "    plugin: schnitzel_stream.nodes.dev:StaticSource",
                "    config:",
                "      packets: []",
                "  - id: out",
                "    kind: sink",
                "    plugin: schnitzel_stream.nodes.dev:PrintSink",
                "edges:",
                "  - from: src",
                "    to: out",
                "config: {}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    bad = repo_root / "bad.yaml"
    bad.write_text(
        "version: 2\nnodes:\n  - id: only\n    kind: source\n    plugin: schnitzel_stream.nodes.dev:StaticSource\nedges:\n  - from: only\n    to: missing\nconfig: {}\n",
        encoding="utf-8",
    )

    ok = wizard_ops.validate_graph_file(repo_root=repo_root, spec_path=str(good))
    fail = wizard_ops.validate_graph_file(repo_root=repo_root, spec_path=str(bad))

    assert ok.ok is True
    assert fail.ok is False
    assert "missing" in fail.error or "not found" in fail.error
